SELECT INS.NAME, INS.DATETIME AS START_DATE
FROM ANIMAL_INS INS
LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL  -- 아직 입양되지 않은 동물
ORDER BY INS.DATETIME ASC     -- 보호 시작일 순으로 정렬
LIMIT 3; 