# SELECT F.FLAVOR
# FROM FIRST_HALF AS F
# WHERE F.TOTAL_ORDER > 3000 AND 
# F.FLAVOR IN (SELECT I.FLAVOR FROM ICECREAM_INFO AS I WHERE I.INGREDIENT_TYPE = 'fruit_based')
# ORDER BY F.TOTAL_ORDER ASC;

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I
    ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND
I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC