SELECT
    DISTINCT C.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY R
WHERE
    C.CAR_TYPE = '세단' AND MONTH(R.START_DATE) = '10' AND C.CAR_ID = R.CAR_ID
ORDER BY
    C.CAR_ID DESC