SELECT
    b.CATEGORY,
    SUM(s.SALES) TOTAL_SALES
FROM
    BOOK b,
    BOOK_SALES s
WHERE
    b.BOOK_ID = s.BOOK_ID
    AND s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    b.CATEGORY
ORDER BY
    b.CATEGORY